* Fix for --clear-cache option and test * Improvement for kscript based on kotlinc
Signed-off-by: Marcin Kuszczak <1508798+aartiPl@users.noreply.github.com>

diff --git a/src/kscript b/src/kscript
--- a/src/kscript
+++ b/src/kscript
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
 
-absolute_path() {
+resolveAbsolutePath() {
     # if the given path to the kscript launcher is absolute (i.e. it is either starting with / or a
     # 'letter:/' when using gitbash on windows) it is returned unchanged, otherwise we construct an absolute path
     [[ $1 = /* ]] || [[ $1 =~ ^[A-z]:/ ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
-resolve_symlink() (
+resolveSymlinks() (
     if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
     sym_resolved=$(readlink ${minusFarg} $1)
 
@@ -17,21 +17,79 @@ resolve_symlink() (
     fi
 )
 
-ABS_KSCRIPT_PATH=$(resolve_symlink $(absolute_path $0))
+findJavaVersion() {
+    # Note that this only loads the first component of the version, so "1.8.0_265" -> "1".
+    # But it's fine because major version is 9 for JDK 9, and so on.
+    regex='^.*version "([[:digit:]]+).*$'
+    while read -r line; do
+        if [[ "$line" =~ $regex ]]; then
+            echo ${BASH_REMATCH[1]}
+        fi
+    done <<< $("${JAVACMD:=java}" -version 2>&1)
+}
 
-JAR_PATH=$(dirname $(dirname "$ABS_KSCRIPT_PATH"))/lib
+# Resolve KSCRIPT_HOME
+KSCRIPT_HOME=$(dirname $(dirname $(resolveSymlinks $(resolveAbsolutePath $0))))
+KSCRIPT_LIB="$KSCRIPT_HOME/lib"
+
+# Resolve JAVA_CMD
+if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
+    JAVACMD="$JAVA_HOME/bin/java"
+fi
+
+# Resolve KOTLIN_HOME
+KOTLIN_HOME=${KOTLIN_HOME:=$(dirname $(dirname $(resolveSymlinks $(resolveAbsolutePath $(which kotlinc)))))}
 
 # OSTYPE can be: linux*, freebsd, darwin*, cygwin, msys
 if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
-  JAR_PATH=$(cygpath -w "${JAR_PATH}")
+  KSCRIPT_LIB=$(cygpath -w "${KSCRIPT_LIB}")
   true
 fi
 
 ## expose the name of the script being run to the script itself
 export KSCRIPT_FILE="$1"
 
+[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx256M -Xms32M"
+
+declare -a java_args
+declare -a kotlin_args
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -D*)
+      java_args=("${java_args[@]}" "$1")
+      shift
+      ;;
+    -J*)
+      java_args=("${java_args[@]}" "${1:2}")
+      if [ "x${1:2}" = "x" ]; then
+        echo "error: empty -J argument"
+        exit 1
+      fi
+      shift
+      ;;
+    *)
+      kotlin_args=("${kotlin_args[@]}" "$1")
+      shift
+      ;;
+  esac
+done
+
+# Additional Java args
+java_version="$(findJavaVersion)"
+if [[ $java_version -ge 9 ]]; then
+  # Workaround the illegal reflective access warning from ReflectionUtil to ResourceBundle.setParent, see IDEA-248785.
+  java_args=("${java_args[@]}" "--add-opens" "java.base/java.util=ALL-UNNAMED")
+fi
+
+if [[ $java_version < 13 ]]; then
+  java_args=("${java_args[@]}" "-noverify")
+fi
+
+java_args=("${java_args[@]}" "-Dkotlin.home=${KOTLIN_HOME}")
+
 ## run it using command substitution to have just the user process once kscript is done
-COMMAND=$("java" -classpath "$JAR_PATH/*" io.github.kscripting.kscript.KscriptKt "$OSTYPE" "$@")
+COMMAND=$("${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -classpath "$KSCRIPT_LIB/*" io.github.kscripting.kscript.KscriptKt "$OSTYPE" "${kotlin_args[@]}")
 RESULT=$?
 
 if [ ! $RESULT -eq 0 ]; then
