Test fix.
Signed-off-by: Marcin Kuszczak <1508798+aartiPl@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -64,23 +64,23 @@ jobs:
           
           echo "OsType:         $OSTYPE"
           
-          ./gradlew clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
+          gradle clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
           
           if [[ "$OSTYPE" == "linux"* ]]; then
             echo "Linux test..."
-            ./gradlew -DosType=$OSTYPE -DincludeTags='posix | linux' integration
+            gradle -DosType=$OSTYPE -DincludeTags='posix | linux' integrationTest
           elif [[ "$OSTYPE" == "darwin"* ]]; then
             echo "MacOs test..."
-            ./gradlew -DosType=$OSTYPE -DincludeTags='posix | macos' integration
+            gradle -DosType=$OSTYPE -DincludeTags='posix | macos' integrationTest
           elif [[ "$OSTYPE" == "cygwin" ]]; then
             echo "Cygwin test..."
-            ./gradlew -DosType=$OSTYPE -DincludeTags='posix | cygwin' integration
+            gradle -DosType=$OSTYPE -DincludeTags='posix | cygwin' integrationTest
           elif [[ "$OSTYPE" == "msys" ]]; then
             echo "MSys test..."
-            ./gradlew -DosType=$OSTYPE -DincludeTags='posix | msys' integration
+            gradle -DosType=$OSTYPE -DincludeTags='posix | msys' integrationTest
           elif [[ "$OSTYPE" == "freebsd"* ]]; then
             echo "FreeBsd test..."
-            ./gradlew -DosType=$OSTYPE -DincludeTags='posix' integration      
+            gradle -DosType=$OSTYPE -DincludeTags='posix' integrationTest
           else
             echo "Unknown OS"
             exit 1
@@ -91,9 +91,9 @@ jobs:
         shell: cmd
         run: |
           echo "Windows test..."
-          .\gradlew.bat clean assemble test
+          gradle clean assemble test
           if %errorlevel% neq 0 exit /b %errorlevel%
-          .\gradlew.bat -DosType=windows -DincludeTags="windows" integration
+          gradle -DosType=windows -DincludeTags="windows" integrationTest
 
       - name: Install Cygwin (only Windows)
         if: matrix.variant == 'cygwin'
@@ -107,5 +107,5 @@ jobs:
           echo "Cygwin test..."
           echo "Changing directory to $GITHUB_WORKSPACE ..."
           cd $GITHUB_WORKSPACE
-          ./gradlew clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
-          ./gradlew -DosType=$OSTYPE -DincludeTags='posix | cygwin' integration
+          gradle clean assemble test || { echo 'Compilation or Unit tests failed' ; exit 1; }
+          gradle -DosType=$OSTYPE -DincludeTags='posix | cygwin' integrationTest
